gold/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('qizil.urls')),
    path('users/', include('users.urls')),
    path('captcha', include('captcha.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qizil/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.index, name='index'),
    path('gold/<str:pk>/', views.gold , name='gold'),
    path('goldform/', views.addgold, name='addgold'),
    path('editgold/<str:pk>/', views.editgold, name='editgold'),
    path('delgold/<str:pk>/', views.delgold, name='delgold'),



]

users/urls.py
from django.urls import path
from . import views
urlpatterns= [
    path('login/', views.loginpage, name='login'),
    path('logout/', views.logoutpage, name='logout'),
    path('register/', views.registerpage, name='register'),
    path('profile/<str:pk>/', views.profile, name='profile'),
    path('profileform/<str:pk>/', views.profileform, name='profileform'),

]

qizil/models.py
from django.db import models
from django.contrib.auth.models import User
from users.models import Profile



class Gold(models.Model):
    name = models.CharField(max_length=20)
    gram = models.FloatField()
    price = models.FloatField()
    prob = models.FloatField()
    picture = models.ImageField(upload_to='images')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']


    def __str__(self):
        return self.name


class Comment(models.Model):
    comment = models.ForeignKey(Gold, on_delete=models.CASCADE, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    test = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    text = models.TextField()

    def __str__(self):
        return self.text

users/models.py
from django.db import models
from django.contrib.auth.models import User

class Username1(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    surname = models.CharField(max_length=20)

    def __str__(self):
        return self.user


class Profile(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    surname = models.CharField(max_length=20)
    bio = models.TextField()
    location = models.CharField(max_length=20, blank=True)
    email = models.EmailField(blank=True)
    skill = models.TextField()
    pic = models.ImageField(upload_to='images/', null=True, blank=True)

    def __str__(self):
        return self.name

qizil/forms.py
from . models import Gold, Comment

from django.forms import ModelForm
from django import forms
from captcha.fields import CaptchaField



class Goldform(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Gold
        fields = '__all__'

class Commentform(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Comment
        fields = ['text', 'captcha']

users/forms.py
from django.forms import ModelForm, TextInput
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . models import Profile

class Userform(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','password1','password2']
        widgets = {
            'username':TextInput(attrs={
                'class':"form-control",
                'style':"max-width: 300px;",
                'placeholder':'username'
            })
        }


class Profileform(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude =['owner']

qizil/views.py
from django.shortcuts import render, redirect
from . models import Gold, Comment
from . forms import Goldform, Commentform
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q


def index(request):
    search = ''
    if request.GET.get('search'):
        search = request.GET.get('search')

    gold = Gold.objects.filter(Q(name__icontains=search) |
                               Q(gram__icontains=search)
                               )
    result = 5
    page = request.GET.get('pager')
    pagi = Paginator(gold, result)
    try:
        gold = pagi.page(page)
    except PageNotAnInteger:
        page = 1
        gold = pagi.page(page)
    except EmptyPage:
        page = pagi.num_pages
        gold = pagi.page(page)
    context ={'gold': gold, 'pagi' : pagi, 'search' : search}
    return render(request, 'qizil/index.html', context)


def gold(request, pk):
    goldid = Gold.objects.get(id=pk)
    form = Commentform()
    if request.method == 'POST':
        form = Commentform(request.POST)
        if form.is_valid():
            human = True
            comment = form.save(commit=False)
            comment.comment = goldid
            comment.owner = request.user
            comment.save()
    else:
        form = Commentform()
        print('Wrong CAPTCHA')
    context = {'goldid': goldid, 'form': form}
    return render(request, 'qizil/gold_info.html', context)


def addgold(request):
    page = 'new'
    form = Goldform()
    if request.method == 'POST':
        form = Goldform(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('index')
    context = {'form': form, 'page': page}
    return render(request, 'qizil/goldform.html', context)


def editgold(request, pk):
    gold = Gold.objects.get(id=pk)
    form = Goldform(instance=gold)
    if request.method == 'POST':
        form = Goldform(request.POST,request.FILES ,instance=gold, )
        form.save()
        return redirect('index')

    context = {'form': form}
    return render(request, 'qizil/goldform.html', context)


def delgold(request, pk):
    page = 'delete'
    gold = Gold.objects.get(id=pk)
    form = Goldform()
    if request.method == 'POST':
        form = Goldform(instance=gold)
        gold.delete()
        return  redirect('index')
    context = {'gold': gold, 'page': page}
    return render(request, 'qizil/goldform.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from . forms import Userform, Profileform
from . models import Profile




def registerpage(request):
    if request.user.is_authenticated:
        return redirect('index')
    page = 'register'
    form = Userform()
    if request.method == 'POST':
        form = Userform(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    context = {'form': form, 'page' : page}
    return render(request, 'users/login_register.html', context)

def loginpage(request):
    if request.user.is_authenticated:
        return redirect('index')
    page = 'login'
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = User.objects.get(username=username)
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            print('no user')
    context = {'page' : page}
    return render(request, 'users/login_register.html', context)

def logoutpage(request):
    logout(request)
    return redirect('index')


def profile(request, pk):
    user = User.objects.get(id=pk)
    profile = Profile.objects.get(id=pk)
    '''if request.user == profile.owner:
        print(request.user)
    else:
        return redirect('index')
        print('not owner')'''
    context = {'user': user}
    return render(request, 'users/profile.html', context)

def profileform(request, pk):
    profile = Profile.objects.get(id=pk)
    form = Profileform(instance=profile)
    if request.user == profile.owner:
        print(request.user)
    else:
        return redirect('index')
        print('This is not yours')
    if request.method == 'POST':
        form = Profileform(request.POST,request.FILES,instance=profile)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.owner = request.user
            print(profile.owner)
            profile.save()
            return redirect('index')
    context = {'form' : form}
    return render(request, 'users/user-form.html', context)

qizil/templates/qizil/gold_info.html
{% extends 'qizil/main.html' %}
{% load static %}
{% block content %}
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
  <!-- Icon - IconMonster -->
  <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
  <!-- Mumble UI -->
  <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="{% static 'css/app.css' %}" />

  <title>DevSearch - Connect with Developers!</title>
</head>

<body>
  <!-- Header Section -->


  <!-- Main Section -->
  <main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column">
                <div class="card project">
                  <a href="single-project.html" class="project">
                    <img class="project__thumbnail" src="{{goldid.picture.url}}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{goldid.price}}$</h3>
                      <p><a class="project__author" href="profile.html">{{goldid.name}}</a></p>



                      </div>
                    </div>
                  </a>
                </div>
              </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">GOLD</h3>
            <p class="devInfo__about">
                 <h3>{{goldid.name}}</h3>
            </p>
          </div>
          <div class="comments">



            <form class="form" action="" method="POST">
              {% for i in form %}
                {% csrf_token %}
              <div class="form__field">
                {{i}}
              </div>
                {% endfor %}
              <input class="btn btn--sub btn--lg" type="submit" value="Add  Comments" />
            </form>
    <div class="commentList">
        {% for i in goldid.comment_set.all %}
              <div class="comment">
                <a href="{% url 'profile' i.owner.id %}">
                  <img class="avatar avatar--md"
                    src="{{i.test.profile.pic.url}}" alt="us" />
                </a>
                <div class="comment__details">
                  <a href="{% url 'profile' i.owner.id %}" class="comment__author">{{i.owner}}</a>
                  <p class="comment__info">
                   {{i.text}}
                  </p>
                </div>
              </div>
        {% endfor %}
    </div></div>

          </div>





            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</body>

</html>
 {% endblock content %}

qizil/templates/qizil/goldform.html
{% if page == 'new' %}
<form  method="post" enctype="multipart/form-data" >
    {% csrf_token%}
    {{form.as_p}}
    <input type="submit" value="submit">
</form>
{% else %}

<form  method="post" enctype="multipart/form-data">
    {% csrf_token%}
    {{form.as_p}}
    <input type="submit" value="submit">
</form>

{% endif %}
{% if page == 'delete' %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{captcha}}
<h2>Are you sure to delete this project ?</h2>
    <input type="submit" value="Yes">
    <a href="{% url 'index' %}"></a> <input type="reset"value="No">
</form>
{% endif %}

qizil/templates/qizil/index.html
{% extends 'qizil/main.html' %}
{% block content %}
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
  <!-- Icon - IconMonster -->
  <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
  <!-- Mumble UI -->
  <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="{% static 'css/app.css' %}" />
   <link rel="stylesheet" href="{% static 'css/main.css' %}"/>

  <title>DevSearch - Connect with Developers!</title>
</head>

<body>


  <!-- Main Section -->
  <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>Search GOLD Here <span>Luxury Gold</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Gold </label>
              <input class="input input--text" id="formInput#search" type="text" name="search"
                placeholder="Search by gold name"  />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">
          {% for i in gold %}
           <div class="column">
                <div class="card project">
                  <a href="{% url 'gold' i.id %}" class="project">
                    <img  class="project__thumbnail" src="{{i.picture.url}}" style="max-height: 100%;" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{i.name}}</h3>
                      <p><a class="project__author" href=""></a></p>


                      </div>
                    </div>
                  </a>
                </div>
           {% endfor %}
              </div>



</div>
      </div>
    </section>

    <div class="pagination_section">
      <ul class="container">
        {% if gold.has_previous %}
        <a href="?pager={{gold.previous_page_number}}" class="btn page-link btn--sub">Prev</a>
        {% endif %}
     {% for pager in pagi.page_range %}
        <a href="?pager={{pager}}" class="btn page-link btn--sub">{{pager}}</a>
      {% endfor %}
        {% if gold.has_next %}
        <a href="?pager={{gold.next_page_number}}" class="btn page-link btn--sub">Next</a>
        {% endif %}

      </ul>

    </div>


  </main>
</body>

</html>
{% endblock content %}

qizil/templates/qizil/main.html
 <header class="header">
    <div class="container container--narrow">
      <a href="/" class="header__logo">
        <img src="images/logo.svg" alt="GoldSearch Logo" />
      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          <li class="header__menuItem"><a href="{% url 'addgold' %}">Add new gold</a></li>
          <li class="header__menuItem"><a href="{% url 'index' %}">Projects</a></li>
          <li class="header__menuItem"><a href="inbox.html">Inbox</a></li>
          <li class="header__menuItem"><a href="{% url 'profile' user.id %} ">My Account</a></li>
          {% if user.is_authenticated %}
          <li class="header__menuItem"><a href="{% url 'logout' %}" class="btn btn--sub">Logout</a></li>
          <li class="header__menuItem"><a href="{% url 'profileform' user.id %}" class="">{{user}}</a></li>
          {% else %}
          <li class="header__menuItem"><a href="{% url 'login' %}" class="btn btn--sub">Login</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </header>
{% block content %} {% endblock content %}

users/templates/users/login_register.html
{% load static  %}
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/linux.css' %}" />
{% if page == 'register'%}

<div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="card my-5">

          <form class="card-body cardbody-color p-lg-5" method="post" action="{% url 'register' %}">
              {% csrf_token %}


            <div class="text-center">
              <img src="https://cdn.buttercms.com/ib9RVsOKQGerXD8sx6Er" class="img-fluid profile-image-pic img-thumbnail rounded-circle my-3"
                width="200px" alt="profile">
            </div>
               <div class="mb-3">
               {{form.as_p}}
               </div>
              <input type="submit" value="REgister">
           </form>
            </div>

        </div>

      </div>
    </div>
  </div>
{% endif %}




{% if page == 'login' %}

<div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="card my-5">

          <form class="card-body cardbody-color p-lg-5" method="post" action="{% url 'login' %}">
              {% csrf_token %}

            <div class="text-center">
              <img src="https://mau.ru/pub/stars/img/fluffy_cat.jpg" class="img-fluid profile-image-pic img-thumbnail rounded-circle my-3"
                width="200px" alt="profile">
            </div>

                  <div class="mb-3">
              <input type="text" class="form-control" name="username" placeholder="login">
            </div>
             <div class="mb-3">
              <input type="password" class="form-control" name="password" placeholder="parol">
            </div>
           <div class="mb-3">
              <input type="submit" value="Subminator">
            </div>
              <div  class="form-text text-center mb-5 text-dark">Registraciyan yoxdur?
               <a href="{% url 'register' %}" class="text-dark fw-bold"> Hesab Yarat
                </a>
            </div>
          </form>
        </div>

      </div>
    </div>
  </div>
{% endif %}

users/templates/users/logout.html
<h1> This is logout page</h1>

users/templates/users/profile.html
{% extends 'qizil/main.html' %}
{% load static %}

{% block content %}

<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
  <!-- Icon - IconMonster -->
  <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
  <!-- Mumble UI -->
  <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="{% static 'css/app.css' %}" />

  <title>DevSearch - Connect with Developers!</title>
</head>

<body>


  <!-- Main Section -->
  <main class="profile my-md">
      {% for i in user.profile_set.all %}
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{i.pic.url}}" />
              <h2 class="dev__name">{{i.owner}}</h2>
              <p class="dev__title">{{i.name}}, {{i.surname}}</p>
                <p class="dev__title">{{i.email}}</p>
              <p class="dev__location">{{i.location}}</p>
              <ul class="dev__social">
                <li>
                  <a title="Github" href="#" target="_blank"><i class="im im-github"></i></a>
                </li>
                <li>
                  <a title="Stackoverflow" href="#" target="_blank"><i class="im im-stackoverflow"></i></a>
                </li>
                <li>
                  <a title="Twitter" href="#" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                <li>
                  <a title="LinkedIn" href="#" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                <li>
                  <a title="Personal Website" href="#" target="_blank"><i class="im im-globe"></i></a>
                </li>
              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">Haqqimda</h3>
            <p class="devInfo__about">
              {{i.bio}}
              <br />

            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Bacariqlarim</h3>
            <div class="devInfo__skills">
              <div class="devSkill">
                <h4 class="devSkill__title"></h4>
                <p class="devSkill__info">
                  {{i.skill}}
                </p>
              </div>



              <h3 class="devInfo__subtitle">Bashga Bacariqlar</h3>
              <div class="devInfo__otherSkills">
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>Qelyan</small>
                </span>
                  <span class="tag tag--pill tag--sub tag--lg" >
                      <small>Turk Seriallari</small>
                  </span>


              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">

              <div class="column">
                <div class="card project">
                  <a href="single-project.html" class="project">
                    <img class="project__thumbnail" src="images/project-b.png" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">DevSearch UI Design</h3>
                      <p><a class="project__author" href="profile.html">By Shahriar P. Shuvo</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">92%</span> Postitive
                        Feedback (62 Votes)
                      </p>
                      <div class="project__tags">
                        <span class="tag tag--pill tag--main">
                          <small>NextJS</small>
                        </span>
                        <span class="tag tag--pill tag--main">
                          <small>GraphQL</small>
                        </span>
                        <span class="tag tag--pill tag--main">
                          <small>TypeScript</small>
                        </span>
                      </div>
                    </div>
                  </a>
                </div>
              </div>

              <div class="column">
                <div class="card project">
                  <a href="single-project.html" class="project">
                    <img class="project__thumbnail" src="images/project-c.png" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">Another Landing Page</h3>
                      <p><a class="project__author" href="profile.html">By Dennis Ivanov</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">36%</span> Postitive
                        Feedback (18 Votes)
                      </p>
                      <div class="project__tags">
                        <span class="tag tag--pill tag--main">
                          <small>NextJS</small>
                        </span>
                        <span class="tag tag--pill tag--main">
                          <small>GraphQL</small>
                        </span>
                        <span class="tag tag--pill tag--main">
                          <small>TypeScript</small>
                        </span>
                      </div>
                    </div>
                  </a>
                </div>
              </div>

              <div class="column">
                <div class="card project">
                  <a href="single-project.html" class="project">
                    <img class="project__thumbnail" src="images/project-a.png" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">Yoga Studio Landing Page Website and Design</h3>
                      <p><a class="project__author" href="profile.html">By Dennis Ivanov</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">98%</span> Postitive
                        Feedback (72 Votes)
                      </p>
                      <div class="project__tags">
                        <span class="tag tag--pill tag--main">
                          <small>NextJS</small>
                        </span>
                        <span class="tag tag--pill tag--main">
                          <small>GraphQL</small>
                        </span>
                        <span class="tag tag--pill tag--main">
                          <small>TypeScript</small>
                        </span>
                      </div>
                    </div>
                  </a>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
      {% endfor %}
  </main>
</body>

</html>
{% endblock content %}

users/templates/users/user-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>To add form to profile</title>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">

    </form>
    {{user}}
</head>
<body>

</body>
</html>